<script type="text/javascript">
            jQuery(document).ready( function() {
                // binds form submission and fields to the validation engine
                jQuery("#titulo_postgrado").validationEngine();//
            });

            $(document).ready(function(){
               $("#fecha_graduacion").datepicker({
                  yearRange: '1930:2040',
                  showOn: 'both',
                  buttonImage: '<?php echo $this->baseUrl; ?>/js/jqueryui/css/cupertino/images/calendar.png',
                  buttonImageOnly: true,
                  dateFormat: 'yy/mm/dd',
                  changeMonth: true,
                  changeYear: true
               });
            });

            $(document).ready(function() {
				$('#tabla').dataTable( {
					"sScrollY": "80px",
					"bPaginate": true
				} );
			} );
</script>


<div align="center">
<!--   <table width="80%" border="1">
  <tr>
      <td><input id="habilitar" name="habilitar" type="button" value="Habilitar Formulario" onclick="habilitar_postgrado()"/></td>
      <td><input id="deshabilitar" name="deshabilitar" type="button" value="Dehabilitar Formulario" onclick="deshabilitar_postgrado()"/></td>
    <td>&nbsp;</td>
  </tr>
</table>-->

<form id="titulo_postgrado" name="titulo_postgrado" action="" method="post">
<fieldset><legend>TITULO POSTGRADO</legend>
<table width="60%" border="0">
  <tr>
    <td><label>Cedula Identidad</label></td>
    <td>&nbsp;</td>
    <td><label>Nombres y Apellidos</label></td>
  </tr>
  <tr>
    <td><label id="cedula_identidad"><?php echo $this->cedula;?></label></td>
    <td>&nbsp;</td>
    <td><label id="nombres_empleado"><?php echo $this->nombre; ?></label></td>
  </tr>
  <tr>
    <td><label>Nombre Postgrado</label></td>
    <td>&nbsp;</td>
    <td><label>Universidad / Instituto Superior</label></td>
  </tr>
  <tr>
    <td><input id="nombre_postgrado" name="nombre_postgrado" type="text" class="validate[required,custom[onlyLetterSp]] text-input" size="35"/></td>
    <td>&nbsp;</td>
    <td><input id="institucion_postgrado" name="institucion_postgrado" type="text" class="validate[required,custom[onlyLetterSp]] text-input" size="35" /></td>
  </tr>
  <tr>
    <td><label>Titulo Obtenido</label></td>
    <td>&nbsp;</td>
    <td><label>Numero de Registro CONESUP</label></td>
  </tr>
  <tr>
    <td><select id="titulo_obtenido" name="titulo_obtenido" class="validate[required]">
      <option value="">[Seleccionar]</option>
      <option value="Philosophiae Doctor">Phd.</option>
      <option value="Magister">Msc.</option>
      <option value="Especialista">Esp.</option>
      <option value="Diplomado">Dip.</option>
    </select></td>
    <td>&nbsp;</td>
    <td><input id="registro_conesup" name="registro_conesup" type="text" class="validate[required] text-input" size="35"/></td>
  </tr>
  <tr>
      <td><label>Fecha de Graduacion</label></td>
    <td>&nbsp;</td>
    <td><input id="verificar_postgrado" name="verificar_postgrado" type="hidden" value="TRUE"/></td>
  </tr>
  <tr>
    <td><input id="fecha_graduacion" name="fecha_graduacion" type="text" class="validate[required]"/></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
    <br>
</fieldset>
<br>
<table width="80%" border="0">
  <tr>
    <td width="33%">&nbsp;</td>

    <td width="7%"><input class="button small blue" name="" type="submit" value="Ingresar"/></td>
    <td width="16%">&nbsp;</td>
    <td width="6%"><input class="button small blue" name="" type="button" onClick="document.location = '<?php echo $this->url(array('controller' => 'index' ,'action' => 'index'));?>'" value="Cancelar"/></td>
    <td width="38%">&nbsp;</td>
  </tr>
</table>

</form>
</div>

<br>
<br>

<div style="clear:both;"> </div>
<!--    <fieldset><legend>DISCAPACIDADES PERSONAL</legend>-->
        <div align="center">
            <table cellpadding="0" cellspacing="0" border="0" class="display" id="tabla" align="center">
        <thead>
		<tr>
                    <th><label>Id Postgrado</label></th>
                        <th>Cedula de Identidad</th>
                        <th>Nombre del Postgrado</th>
			<th>Universidad / Institucion</th>
                        <th>Titulo Obtenido</th>
                        <th>Registro CONESUP</th>
                        <th>Fecha de Graduacion</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->postgrado as $value): ?>;
		<tr class="gradeA">
			<td><?php echo $this->escape($value->id_postgrado); ?></td>
                        <td><?php echo $this->cedula; ?></td>
			<td><?php echo $this->escape($value->nombre_postgrado); ?></td>
			<td><?php echo $this->escape($value->institucion_postgrado); ?></td>
			<td><?php echo $this->escape($value->titulo_obtenido); ?></td>
                        <td><?php echo $this->escape($value->registro_conesup); ?></td>
			<td><?php echo $this->escape($value->fecha_graduacion); ?></td>
                </tr>
        <?php endforeach; ?>

                </table>
        </div>
<!--                </fieldset>-->
