<link href="<?php echo $this->baseUrl; ?>/js/jqueryui/themes/base/jquery.ui.all.css" media="screen" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl; ?>/js/jqueryui/themes/base/jquery.ui.accordion.css" media="screen" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl; ?>/js/jqueryui/themes/base/demos.css" media="screen" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl; ?>/css/style.css" media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/jqueryui/ui/jquery.ui.core.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/jqueryui/ui/jquery.ui.widget.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/jqueryui/ui/jquery.ui.accordion.js"></script>

<script type="text/javascript">
            jQuery(document).ready( function() {
                // binds form submission and fields to the validation engine
                jQuery("#nominal").validationEngine();//
            });

            $(document).ready(function() {
				$('#tabla').dataTable( {
//					"sScrollY": "80px",
					"bPaginate": true
				} );
			} );
</script>

<div align="center">
<form id="nominal" name="nominal" action="" method="post">
<fieldset><legend>NOMINAL</legend>

<table width="60%" border="0">
  <tr>
    <td><label>Grupo Ocupacional</label></td>
    <td>&nbsp;</td>
    <td><label>Grado Ocupacional</label></td>
  </tr>
  <tr>
    <td><input id="grupo_ocupacional" name="grupo_ocupacional" class="validate[required]" type="text" size="35"/></td>
    <td>&nbsp;</td>
    <td><input id="grado_ocupacional" name="grado_ocupacional" class="validate[required]" type="text" size="35" /></td>
  </tr>
  <tr>
    <td><label>Remuneracion Mensual</label></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><input id="remuneracion_mensual" name="remuneracion_mensual" type="text" class="validate[required,custom[onlyNumberSp]] text-input" size="35"/></td>
    <td>&nbsp;</td>
    <td><input id="esta_activo" name="esta_activo" type="hidden" value="TRUE"/></td>
  </tr>
</table>

<br>

</fieldset>
<br>
<table width="80%" border="0">
  <tr>
    <td width="33%">&nbsp;</td>

    <td width="7%"><input class="button small blue" name="" type="submit" value="Ingresar"/></td>
    <td width="16%">&nbsp;</td>
    <td width="6%"><input class="button small blue" name="" type="button" onClick="document.location = '<?php echo $this->url(array('controller' => 'index' ,'action' => 'index'));?>'" value="Cancelar"/></td>
    <td width="38%">&nbsp;</td>
  </tr>
</table>
</form>
</div>

<div style="clear:both;"> </div>
    <fieldset><legend>DISCAPACIDADES PERSONAL</legend>
        <div align="center">
            <table cellpadding="0" cellspacing="0" border="0" class="display" id="tabla" align="center">
        <thead>
		<tr>
			<th>Id Nominal</th>
                        <th>Grupo Ocupacional</th>
                        <th>Grado Ocupacional</th>
			<th>Remuneración Mensual Unificada</th>
<!--                        <th>Estado Nominal</th>-->
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->nominal as $value): ?>
		<tr class="gradeA">
			<td><?php echo $this->escape($value->id_nominal); ?></td>
			<td><?php echo $this->escape($value->grupo_ocupacional); ?></td>
			<td><?php echo $this->escape($value->grado_ocupacional); ?></td>
			<td><?php echo $this->escape($value->remuneracion_mensual); ?></td>
<!--                        <td><?php echo $this->escape($value->esta_activo); ?></td>-->

                </tr>
        <?php endforeach; ?>
                </table>
        </div>
         </fieldset>