<style type="">
a:link,
a:visited
{
color: #0398CA;
}

span#zf-name
{
color: #91BE3F;
}

div#welcome
{
background-color: #E7E8E9;
background-image: url('../images/fondopage.jpg');
background-repeat: repeat;
background-position: left top;
font-family: Verdana, Arial, sans-serif;
font-size: 13px;
padding: 0;
margin: 0;
color: #555;
line-height: 17px;
}

div#more-information
{
background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
height: 9%;
background-color: #E7E8E9;
}
</style>
<br/>
<br/>
<center>

<div id="welcome">
<br>
<br>
<br>
<font size="5">
    <h1>SGMAS - <span id="zf-name">UPS</span></h1>
</font>
<!--    <h1>SGMAS - <span id="zf-name">UPS</span></h1>-->
<br>
<h3>Sistema de Gestión Médico para Áreas de Salud</h3>
<br>
<br>
<br>
<h3>MODULO DE GESTION DE TALENTO HUMANO</h3>
<br>
<h4>Desarrollado por: </h4>
<h4>Fabricio W Toapanta M.</h4>
<h4>Washington A Lascano B.</h4>
<br>
<div id="more-information">
<p><img alt=""  src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
<p>
    Helpful Links: <br />
    <a href="http://ups.edu.ec/">UNIVERSIDAD POLITECNICA SALESIANA</a> |
    <a href="http://msp.gob.ec/">DIRECCION PROVINCIAL DE SALUD DE PICHINCHA</a>
</p>
</div>
</div>

</center>