<script type="text/javascript">
            jQuery(document).ready( function() {
                // binds form submission and fields to the validation engine
                jQuery("#titulo_universitario").validationEngine();//
            });

            $(document).ready(function(){
               $("#fecha_graduacion").datepicker({
                  yearRange: '1930:2040',
                  showOn: 'both',
                  buttonImage: '<?php echo $this->baseUrl; ?>/js/jqueryui/css/cupertino/images/calendar.png',
                  buttonImageOnly: true,
                  dateFormat: 'yy/mm/dd',
                  changeMonth: true,
                  changeYear: true
               });
            });

             $(document).ready(function() {
				$('#tabla').dataTable( {
					"sScrollY": "80px",
					"bPaginate": true
				} );
			} );
</script>


<div align="center">
<!--   <table width="80%" border="1">
  <tr>
    <td><input id="habilitar" name="habilitar" type="button" value="Habilitar Formulario" onclick="habilitar()"/></td>
    <td><input id="deshabilitar" name="deshabilitar" type="button" value="Dehabilitar Formulario" onclick="deshabilitar()"/></td>
    <td>&nbsp;</td>
  </tr>
</table>-->

<form id="titulo_universitario" name="titulo_universitario" action="" method="post">
<fieldset><legend>TITULO UNIVERSITARIO</legend>
<table width="60%" border="0">
  <tr>
    <td><label>Cedula Identidad</label></td>
    <td>&nbsp;</td>
    <td><label>Nombres y Apellidos</label></td>
  </tr>
  <tr>
    <td><label id="cedula_identidad"><?php echo $this->cedula;?></label></td>
    <td>&nbsp;</td>
    <td><label id="nombres_empleado"><?php echo $this->nombre; ?></label></td>
  </tr>
  <tr>
    <td><label>Título</label></td>
    <td>&nbsp;</td>
    <td><label>Universidad / Instituto Superior</label></td>
  </tr>
  <tr>
    <td><input id="titulo_universitario" name="titulo_universitario" type="text" class="validate[required,custom[onlyLetterSp]] text-input" size="35"/></td>
    <td>&nbsp;</td>
    <td><input id="universidad_institucion" name="universidad_institucion" type="text" class="validate[required,custom[onlyLetterSp]] text-input" size="35" /></td>
  </tr>
  <tr>
    <td><label>País</label></td>
    <td>&nbsp;</td>
    <td><label>Ciudad / Provincia</label></td>
  </tr>
  <tr>
    <td><input id="pais_universidad" name="pais_universidad" type="text" class="validate[required,custom[onlyLetterSp]] text-input" size="35"/></td>
    <td>&nbsp;</td>
    <td><input id="ciudad_universidad" name="ciudad_universidad" type="text" class="validate[required,custom[onlyLetterSp]] text-input" size="35"/></td>
  </tr>
  <tr>
    <td><label>Numero de Registro CONESUP</label></td>
    <td>&nbsp;</td>
    <td><label>Fecha de Graduacion</label></td>
  </tr>
  <tr>
    <td><input id="registro_conesup" name="registro_conesup" type="text" class="validate[required] text-input"/></td>
    <td>&nbsp;</td>
    <td><input id="fecha_graduacion" name="fecha_graduacion" type="text" class="validate[required]"/></td>
  </tr>
  <tr>
    <td><input id="verificar_titulo" name="verificar_titulo" type="hidden" value="TRUE"/></td>
    <td>&nbsp;</td>
    <td></td>
  </tr>
</table>
    <br>
</fieldset>
<br>
<table width="80%" border="0">
  <tr>
    <td width="33%">&nbsp;</td>

    <td width="7%"><input class="button small blue" name="" type="submit" value="Ingresar"/></td>
    <td width="16%">&nbsp;</td>
    <td width="6%"><input class="button small blue" name="" type="button" onClick="document.location = '<?php echo $this->url(array('controller' => 'docenciaUniversitaria' ,'action' => 'ingresar-docencia'));?>'" value="Siguiente"/></td>
    <td width="38%">&nbsp;</td>
  </tr>
</table>
<br>


 <div style="clear:both;"> </div>
<!--    <fieldset><legend>DISCAPACIDADES PERSONAL</legend>-->
        <div align="center">
            <table cellpadding="0" cellspacing="0" border="0" class="display" id="tabla" align="center">
        <thead>
		<tr>
                    <th><label>Id Titulo</label></th>
                        <th>Cedula de Identidad</th>
                        <th>Titulo Universitario</th>
			<th>Universidad / Institucion</th>
                        <th>Pais Universidad</th>
                        <th>Ciudad Universidad</th>
			<th>Registro CONESUP</th>
                        <th>Fecha de Graduacion</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->titulo as $value): ?>;
		<tr class="gradeA">
			<td><?php echo $this->escape($value->id_universitario); ?></td>
                        <td><?php echo $this->cedula; ?></td>
			<td><?php echo $this->escape($value->titulo_universitario); ?></td>
			<td><?php echo $this->escape($value->universidad_institucion); ?></td>
			<td><?php echo $this->escape($value->pais_universidad); ?></td>
                        <td><?php echo $this->escape($value->ciudad_universidad); ?></td>
			<td><?php echo $this->escape($value->registro_conesup); ?></td>
			<td><?php echo $this->escape($value->fecha_graduacion); ?></td>
                </tr>
        <?php endforeach; ?>

                </table>
        </div>
<!--                </fieldset>-->

</form>
</div>