<script type="text/javascript">
            jQuery(document).ready( function() {
                // binds form submission and fields to the validation engine
                jQuery("#funcion").validationEngine();//
            });

             $(document).ready(function() {
				$('#tabla').dataTable( {
//					"sScrollY": "80px",
					"bPaginate": false
				} );
			} );
</script>


<div align="center">
<form id="funcion" name="funcion" action="" method="post">
<fieldset><legend>FUNCION QUE DESEMPEÑA</legend>
     <input name="id_funcion" readonly="readonly" id="id_funcion" value="<?php echo $this->escape($this->id_funcion); ?>" size="10" type="text"/>
<table width="60%" border="0">
  <tr>
    <td><label>Cedula Identidad</label></td>
    <td>&nbsp;</td>
    <td><label>Nombres y Apellidos</label></td>
  </tr>
  <tr>
    <td><label id="cedula_identidad"><?php echo $this->cedula;?></label></td>
    <td>&nbsp;</td>
    <td><label id="nombres_empleado"><?php echo $this->nombre; ?></label></td>
  </tr>
  <tr>
    <td><label>Cargo</label></td>
    <td>&nbsp;</td>
    <td><label>Puesto Institucional</label></td>
  </tr>
  <tr>
    <td><select id="cargo" name="cargo" class="validate[required]">
      <option value="">[Seleccionar]</option>
      <option value="ADMINISTRATIVO">ADMINISTRATIVO</option>
      <option value="PERSONAL DE SALUD">PERSONAL DE SALUD</option>
      <option value="MANTENIMIENTO">MANTENIMIENTO</option>
      <option value="OTROS">OTROS</option>

	</select></td>
    <td>&nbsp;</td>
    <td><select id="id_puesto" name="id_puesto" class="validate[required] text-input">
        <option value="">[Seleccionar]</option>
        <?php foreach ($this->puestos as $item) : ?>
        <option value="<?php echo $this->escape($item->id_puesto);?>"><?php echo $this->escape($item->puesto_institucional);?></option>
       <?php endforeach; ?>
	</select></td>
  </tr>
  <tr>
    <td><label>Especialidad</label></td>
    <td>&nbsp;</td>
    <td><label>Departamento</label></td>
  </tr>
  <tr>
    <td><select id="id_especialidad" name="id_especialidad" class="validate[required] text-input">
        <option value="">[Seleccionar]</option>
        <?php foreach ($this->especialidades as $item) : ?>
        <option value="<?php echo $this->escape($item->id_especialidad);?>"><?php echo $this->escape($item->tipo_especialidad);?></option>
       <?php endforeach; ?>
    </select></td>
    <td>&nbsp;</td>
    <td><input id="departamento" name="departamento" type="text" class="validate[required] text-input" size="35" onkeyup="this.value=this.value.toUpperCase()"/></td>
  </tr>
  <tr>
      <td><label>Oficina / Consultorio</label></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><input id="oficina_consultorio" name="oficina_consultorio" type="text" class="validate[required]" size="35" onkeyup="this.value=this.value.toUpperCase()"/></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
    <br>
</fieldset>
<br>
<table width="80%" border="0">
  <tr>
    <td width="33%">&nbsp;</td>

    <td width="7%"><input class="button small blue" name="" type="submit" value="Ingresar"/></td>
    <td width="6%">&nbsp;</td>
    <td width="38%"><input class="button small blue" name="" type="button" onClick="document.location = '<?php echo $this->url(array('controller' => 'Discapacidad' ,'action' => 'ingresar-discapacidad'));?>'" value="Siguiente"/></td>
  </tr>
</table>
</form>
</div>


<div style="clear:both;"> </div>
    <fieldset><legend>DISCAPACIDADES PERSONAL</legend>
        <div align="center">
            <table cellpadding="0" cellspacing="0" border="0" class="display" id="tabla" align="center">
        <thead>
		<tr>
			<th>Id Funcion</th>
                        <th>Cedula de Identidad</th>
                        <th>Cargo que Ejerce</th>
			<th>Puesto Institucional</th>
                        <th>Especialidad</th>
                        <th>Departamento</th>
                        <th>Consultorio / Oficina</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->funciones as $value): ?>
		<tr class="gradeA">
			<td><?php echo $this->escape($value->id_funcion); ?></td>
                        <td><?php echo $this->cedula; ?></td>
			<td><?php echo $this->escape($value->cargo); ?></td>
			<td><?php echo $this->escape($value->puesto_institucional); ?></td>
			<td><?php echo $this->escape($value->tipo_especialidad); ?></td>
                        <td><?php echo $this->escape($value->departamento); ?></td>
                        <td><?php echo $this->escape($value->oficina_consultorio); ?></td>
                </tr>
        <?php endforeach; ?>

                </table>
        </div>
                </fieldset>