<script type="text/javascript">
            jQuery(document).ready( function() {
                // binds form submission and fields to the validation engine
                jQuery("#canton").validationEngine();//
            });

            $(document).ready(function() {
				$('#tabla').dataTable( {
//					"sScrollY": "140px",
					"bPaginate": true
				} );
			} );
</script>       


<div align="center">
<form id="canton" name="canton" action="" method="post">
    <fieldset><legend>CANTON</legend>

<table width="200" border="0">
  <tr>
    <td><label>Provincia</label></td>
  </tr>
  <tr>
      <td><select id="id_provincia" name="id_provincia" class="validate[required]">
      <option value="">[Seleccionar]</option>
       <?php foreach ($this->provincia as $item) : ?>
      <option value="<?php echo $this->escape($item->id_provincia);?>"><?php echo $this->escape($item->nombre_provincia);?></option>
       <?php endforeach; ?>
	</select></td>
  </tr>
  <tr>
    <td><label>Nombre Canton</label></td>
  </tr>
  <tr>
    <td><input id="nombre_canton" name="nombre_canton" type="text" class="validate[required] text-input" onkeyup="this.value=this.value.toUpperCase()"/></td>
  </tr>
</table>
<br>
</fieldset>

    <br>
  <table>
   <tr>
       <td style="width: 261px;">
       </td>
       <td style="width: 198px;" align="center">
           <input class="button small blue" type="submit" value="Agregar"/>
       </td>
       <td style="width: 198px;" align="center" >
           <button  type="button"  class="button small blue" onClick="document.location = '<?php echo $this->url(array('controller' => 'parroquia' ,'action' => 'ingresar-parroquia'));?>'" name="Siguiente">Siguiente</button>
       </td>
       <td style="width: 222px;">
       </td>
   </tr>
  </table>
</form>
</div>


<div id="dt_example" align="center">
<div style="clear:both;"> </div>
   <fieldset><legend>CANTONES</legend>
<!--        <div align="center">-->
            <table cellpadding="0" cellspacing="0" border="0" class="display" id="tabla" align="center">
        <thead>
		<tr>
			<th>Id Canton</th>
                        <th>Provincia</th>
                        <th>Nombre del Canton</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->canton as $value): ?>
		<tr class="grade">
			<td><?php echo $this->escape($value->id_canton); ?></td>
			<td><?php echo $this->escape($value->nombre_provincia); ?></td>
			<td><?php echo $this->escape($value->nombre_canton); ?></td>
                </tr>
        <?php endforeach; ?>

                </table>
<!--        </div>-->
                </fieldset>
</div>

