<script type="text/javascript">
            jQuery(document).ready( function() {
                // binds form submission and fields to the validation engine
                jQuery("#experiencia_laboral").validationEngine();//
            });

$(document).ready(function(){
   $("#fecha_entrada").datepicker({
      yearRange: '1930:2040',
      showOn: 'both',
      buttonImage: '<?php echo $this->baseUrl; ?>/js/jqueryui/css/cupertino/images/calendar.png',
      buttonImageOnly: true,
      dateFormat: 'yy/mm/dd',
      changeMonth: true,
      changeYear: true
   });
})

$(document).ready(function(){
   $("#fecha_salida").datepicker({
      yearRange: '1930:2040',
      showOn: 'both',
      buttonImage: '<?php echo $this->baseUrl; ?>/js/jqueryui/css/cupertino/images/calendar.png',
      buttonImageOnly: true,
      dateFormat: 'yy/mm/dd',
      changeMonth: true,
      changeYear: true
   });
})

$(document).ready(function() {
				$('#tabla').dataTable( {
					"sScrollY": "80px",
					"bPaginate": true
				} );
			} );
</script>

<div align="center">
<!--   <table width="60%" border="1">
  <tr>
      <td><input id="habilitar" name="habilitar" type="button" value="Habilitar Formulario" onclick="habilitar_laboral()"/></td>
      <td><input id="deshabilitar" name="deshabilitar" type="button" value="Dehabilitar Formulario" onclick="deshabilitar_laboral()"/></td>
    <td>&nbsp;</td>
  </tr>
</table>-->

<form id="experiencia_laboral" name="experiencia_laboral" action="" method="post">
<fieldset><legend>EXPERIENCIA LABORAL</legend>
<table width="60%" border="0">
  <tr>
    <td><label>Cedula Identidad</label></td>
    <td>&nbsp;</td>
    <td><label>Nombres y Apellidos</label></td>
  </tr>
  <tr>
    <td><label id="cedula_identidad"><?php echo $this->cedula;?></label></td>
    <td>&nbsp;</td>
    <td><label id="nombres_empleado"><?php echo $this->nombre; ?></label></td>
  </tr>
  <tr>
    <td><label>Institucion / Empresa</label></td>
    <td>&nbsp;</td>
    <td><label>Puesto Anterior</label></td>
  </tr>
  <tr>
    <td><input id="institucion_empresa" name="institucion_empresa" type="text" class="validate[required] text-input" size="35" /></td>
    <td>&nbsp;</td>
    <td><input id="puesto_cargo" name="puesto_cargo" type="text" class="validate[required] text-input" size="35" /></td>
  </tr>
  <tr>
    <td><label>Fecha de Ingreso</label></td>
    <td>&nbsp;</td>
    <td><label>Fecha de Salida</label></td>
  </tr>
  <tr>
    <td><input id="fecha_entrada" name="fecha_entrada" type="text" class="validate[required]" /></td>
    <td>&nbsp;</td>
    <td><input id="fecha_salida" name="fecha_salida" type="text" class="validate[required]"/></td>
  </tr>
  <tr>
    <td><label>Provincia</label></td>
    <td>&nbsp;</td>
    <td><label>Ciudad</label></td>
  </tr>
  <tr>
    <td><select id="id_provincia" name="id_provincia" class="validate[required,min[1]]" onchange="cargarCantones(this)">
     <option value="0">[Seleccionar]</option>
           <?php foreach ($this->provincia as $item) : ?>
            <option value="<?php echo $this->escape($item->id_provincia);?>"><?php echo $this->escape($item->nombre_provincia);?></option>
           <?php endforeach; ?>
    </select></td>
    <td>&nbsp;</td>
    <td><select id="canton" name="id_canton" class="valdate[required]">
      <option value="">[Seleccionar]</option>
    </select></td>
  </tr>
  <tr>
    <td><input id="verificar_experiencia" name="verificar_experiencia" type="hidden" value="TRUE"/></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
    <br>
</fieldset>
<br>
<table width="80%" border="0">
  <tr>
    <td width="33%">&nbsp;</td>

    <td width="7%"><input class="button small blue" name="" type="submit" value="Ingresar"/></td>
    <td width="16%">&nbsp;</td>
    <td width="6%"><input class="button small blue" name="" type="button" onClick="document.location = '<?php echo $this->url(array('controller' => 'Capacitacion' ,'action' => 'ingresar-capacitacion'));?>'" value="Siguiente"/></td>
    <td width="38%">&nbsp;</td>
  </tr>
</table>
</form>
</div>

<div style="clear:both;"> </div>
<!--    <fieldset><legend>DISCAPACIDADES PERSONAL</legend>-->
        <div align="center">
            <table cellpadding="0" cellspacing="0" border="0" class="display" id="tabla" align="center">
        <thead>
		<tr>
			<th>Id Experiencia laboral</th>
                        <th>Cedula de Identidad</th>
                        <th>Institución / Empresa</th>
			<th>Puesto</th>
                        <th>Fecha de Ingreso</th>
                        <th>Fecha de Salida</th>
                        <th>Ciudad</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this-> experiencia as $value): ?>
		<tr class="gradeA">
			<td><?php echo $this->escape($value->id_experiencia_laboral); ?></td>
                        <td><?php echo $this->cedula; ?></td>
			<td><?php echo $this->escape($value->institucion_empresa); ?></td>
			<td><?php echo $this->escape($value->puesto_cargo); ?></td>
			<td><?php echo $this->escape($value->fecha_entrada); ?></td>
                        <td><?php echo $this->escape($value->fecha_salida); ?></td>
                        <td><?php echo $this->escape($value->ciudad); ?></td>
                </tr>
        <?php endforeach; ?>

                </table>
        </div>
<!--                </fieldset>-->