<script type="text/javascript">
            jQuery(document).ready( function() {
                // binds form submission and fields to the validation engine
                jQuery("#docencia_universitaria").validationEngine();//
            });


            $(document).ready(function() {
				$('#tabla').dataTable( {
					"sScrollY": "80px",
					"bPaginate": true
				} );
			} );
</script>

<div align="center">
<!--   <table width="60%" border="1">
  <tr>
      <td><input id="habilitar" name="habilitar" type="button" value="Habilitar Formulario" onclick="habilitar_docencia()"/></td>
      <td><input id="deshabilitar" name="deshabilitar" type="button" value="Dehabilitar Formulario" onclick="deshabilitar_docencia()"/></td>
    <td>&nbsp;</td>
  </tr>
</table>-->

<form id="docencia_universitaria" name="docencia_universitaria" action="" method="post">
<fieldset><legend>DOCENCIA UNIVERSITARIA</legend>
<table width="60%" border="0">
  <tr>
    <td><label>Cedula Identidad</label></td>
    <td>&nbsp;</td>
    <td><label>Nombres y Apellidos</label></td>
  </tr>
  <tr>
    <td><label id="cedula_identidad"><?php echo $this->cedula;?></label></td>
    <td>&nbsp;</td>
    <td><label id="nombres_empleado"><?php echo $this->nombre; ?></label></td>
  </tr>
  <tr>
    <td><label>Nombre de la Institucion</label></td>
    <td>&nbsp;</td>
    <td><label>Tipo Contrato</label></td>
  </tr>
  <tr>
    <td><input id="institucion_docencia" name="institucion_docencia" type="text" class="validate[required,custom[onlyLetterNumber]] text-input" size="35" /></td>
    <td>&nbsp;</td>
    <td><input id="tipo_contrato" name="tipo_contrato" type="text" class="validate[required,custom[onlyLetterSp]] text-input" size="35" /></td>
  </tr>
  <tr>
    <td><label>Catedra a Dictar</label></td>
    <td>&nbsp;</td>
    <td><label>Horas a la Semana</label></td>
  </tr>
  <tr>
    <td><input id="catedra" name="catedra" type="text" class="validate[required] text-input" size="35" /></td>
    <td>&nbsp;</td>
    <td><input id="horas_semana" name="horas_semana" type="text" class="validate[required,custom[onlyNumberSp]] text-input" size="35"/></td>
  </tr>
  <tr>
      <td><input id="esta_activo" name="esta_activo" type="hidden" value="TRUE"/></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
    <br>
</fieldset>
<br>
<table width="80%" border="0">
  <tr>
    <td width="33%">&nbsp;</td>

    <td width="7%"><input class="button small blue" name="" type="submit" value="Ingresar"/></td>
    <td width="16%">&nbsp;</td>
    <td width="6%"><input class="button small blue" name="" type="button" onClick="document.location = '<?php echo $this->url(array('controller' => 'estudiosActuales' ,'action' => 'ingresar-estudios'));?>'" value="Siguiente"/></td>
    <td width="38%">&nbsp;</td>
  </tr>
</table>
</form>
</div>

<div style="clear:both;"> </div>
<!--    <fieldset><legend>DISCAPACIDADES PERSONAL</legend>-->
        <div align="center">
            <table cellpadding="0" cellspacing="0" border="0" class="display" id="tabla" align="center">
        <thead>
		<tr>
			<th>Id Docencia Universitaria</th>
                        <th>Cedula de Identidad</th>
                        <th>Nombre de la Institucion</th>
			<th>Tipo de Nombramiento o Contrato</th>
                        <th>Catedra</th>
                        <th>Horas a la Semana</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->docencia as $value): ?>
		<tr class="grade">
			<td><?php echo $this->escape($value->id_docencia); ?></td>
                        <td><?php echo $this->cedula; ?></td>
			<td><?php echo $this->escape($value->institucion_docencia); ?></td>
			<td><?php echo $this->escape($value->tipo_contrato); ?></td>
			<td><?php echo $this->escape($value->catedra); ?></td>
                        <td><?php echo $this->escape($value->horas_semana); ?></td>
                </tr>
        <?php endforeach; ?>

                </table>
        </div>
<!--                </fieldset>-->
