 <?php
 if ($this->pageCount): ?>
 <div class="paginationControl">
 <!-- Previous page link -->
 <?php if (isset($this->previous)): ?>
   <a onclick="cargarReporte(<?php echo $this->previous; ?>)" style="cursor:pointer; text-decoration: underline;">< Previous</a> |
   <?php else: ?>
   <span class="disabled">< Previous</span> |
 <?php endif; ?>

 <!-- Numbered page links -->
 <?php foreach ($this->pagesInRange as $page): ?>
   <?php if ($page != $this->current): ?>
     <a onclick="cargarReporte(<?php echo $page; ?>)" style="cursor:pointer; text-decoration: underline;"><?php echo $page; ?></a> |
   <?php else: ?>
     <?php echo $page; ?> |
   <?php endif; ?>
 <?php endforeach; ?>

 <!-- Next page link -->
 <?php if (isset($this->next)): ?>
   <a onclick="cargarReporte(<?php echo $this->next; ?>)" style="cursor:pointer; text-decoration: underline;">Next ></a>
 <?php else: ?>
   <span class="disabled">Next ></span>
 <?php endif; ?>
 </div>
 <?php endif; ?>